#ifndef __BLUETOOTH_WIFI_H
#define __BLUETOOTH_WIFI_H
#include "usart.h"
#include "stdarg.h"
#include "string.h"
#include "bsp.h"
typedef enum{FLAG_CLEAR,FLAG_WAITSETTING,FLAG_OK}YSU_FLAG_STATUS;
typedef enum{
	MODE_STOP=0,
	MODE_HELP=1<<0,
	MODE_BLUETOOTH_HELP=1<<1,
	MODE_BLUETOOTH_CTRL=1<<2,
	MODE_TRACK = 1<<3,
	MODE_OBSTACLE_AVOIDANCE = 1<<4,
	MODE_INFRARED_REMOTE_COPNTROL=1<<5,
	MODE_PURSE_LIGHT = 1<<6,
	MODE_ULTRASONIC_DISTANCE=1<<7,
	MODE_BATTERY_POWER=1<<8,
	MODE_DANCE = 1<<9,
	
	MODE_RED_LIGHT = 1<<13,
	MODE_GREEN_LIGHT = 1<<14,
	MODE_BLUE_LIGHT = 1<<15,
	
	MODE_ALL_HIGHEST_SPEED = 1<<20,
	MODE_MAXIMUM_SPEED = 1<<21,
	MODE_GENERAL_SPEED = 1<<22,
	MODE_MINIMUM_SPEED = 1<<23,
	
	MODE_BLUTOOTH_CTL_FRONT = 1 << 26,
	MODE_BLUTOOTH_CTL_BACK = 1 << 27,
	MODE_BLUTOOTH_CTL_LEFT = 1 << 28,
	MODE_BLUTOOTH_CTL_RIGHT = 1 << 29,
	
}YSU_MODE_STATUS;
void USART2_Config(u32 bound);
void u2printf(char* fmt, ...);
#endif 
